version: '3.4'

services:
  desafio.webapi:
    image: ${DOCKER_REGISTRY-}desafiowebapi
    build:
      context: .
      dockerfile: src/Desafio.WebApi/Dockerfile
    ports: 
       - 49524:443
    networks:
        - my-network-name

  desafio.qeue.consumer:
    image: ${DOCKER_REGISTRY-}desafioqeueconsumer
    build:
      context: .
      dockerfile: src/Desafio.Qeue.Consumer/Dockerfile
    networks:
        - my-network-name

  rabbitmq: 
    container_name: bunny
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    image: rabbitmq:3-management-alpine
    networks:
        - my-network-name
  
  desafio-db:
    container_name: desafio-db
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "@Reforma12345_super"
      ACCEPT_EULA: "Y"
    networks:
        - my-network-name

networks:
    my-network-name:
        driver: bridge

